azure:
  free_disk_space: true
choco:
- cuda --version=11.8.0.52206
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
os_version:
  linux_64: cos7
  linux_ppc64le: alma8
  linux_aarch64: alma8
